### ISSUE TITLE
Can't find `config_template.json`

### ISSUE THREAD

**Issue by jernejmarcic** [raffaem/waybar-mediaplayer#1]
I might be stupid or misunderstanding the README, however I cannot find hte `config_template.json` anywhere?
I searcher for it on the internet and I could not find it either, sorry if i'm wrong.

**Comment by raffaem** [comment]
The README is outdated, I'll update it

**Comment by raffaem** [comment]
> I might be stupid or misunderstanding the README, however I cannot find hte `config_template.json` anywhere? I searcher for it on the internet and I could not find it either, sorry if i'm wrong.

The README has been updated. Can you test the new instructions please?

**Comment by raffaem** [comment]
Opened different issues for the remaining bugs.
